package Visual;

import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author david
 */
public class Inicio extends javax.swing.JFrame {
   //Variables de la posición
        int xMouse, yMouse;     
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        centrarTxt();
        FechaYHora();
    }
    
    public void FechaYHora(){
       // Codigo para la fecha    
        LocalDate now = LocalDate.now();
        int year = now.getYear();
        int dia = now.getDayOfMonth();
        int month = now.getMonthValue();
        String[] meses = {"Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre"
            ,"Octubre","Noviembre","Diciembre"};
        txtfecha.setText("Fecha: "+dia+" de "+meses[month - 1]+" de "+year);
   
    //Codigo para la hora
            DateTimeFormatter formateador = DateTimeFormatter.ofPattern("HH:mm:ss");
        Runnable runnable = new Runnable() {
        @Override
        public void run() {
            while (true) {
                try {
                    Thread.sleep(500);
                    txthora.setText(formateador.format(LocalDateTime.now()));
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        }
    };
    Thread hilo = new Thread(runnable);
    hilo.start();
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jlNomAdmin = new javax.swing.JLabel();
        jbCerrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txthora = new javax.swing.JLabel();
        txtfecha = new javax.swing.JLabel();
        jlApeAdmin = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtCargoAdmin = new javax.swing.JLabel();
        jpPrincipal = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jpUsuarios = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jpreportes = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jpSucursal = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jpCerrarSesion = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(13, 71, 161));
        panel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelMouseDragged(evt);
            }
        });
        panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelMousePressed(evt);
            }
        });
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Usuario");
        panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 60, 30));

        jlNomAdmin.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jlNomAdmin.setForeground(new java.awt.Color(255, 255, 255));
        jlNomAdmin.setText("Nombre");
        panel.add(jlNomAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 190, 30));

        jbCerrar.setBackground(new java.awt.Color(204, 0, 0));
        jbCerrar.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jbCerrar.setForeground(new java.awt.Color(255, 255, 255));
        jbCerrar.setText("X");
        jbCerrar.setBorder(null);
        jbCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCerrarActionPerformed(evt);
            }
        });
        panel.add(jbCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 30, 30));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 30));

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txthora.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        txthora.setForeground(new java.awt.Color(255, 255, 255));
        txthora.setText("Hora");
        jPanel2.add(txthora, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 120, 30));

        txtfecha.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        txtfecha.setForeground(new java.awt.Color(255, 255, 255));
        txtfecha.setText("Fecha:");
        jPanel2.add(txtfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 290, 30));

        jlApeAdmin.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jlApeAdmin.setForeground(new java.awt.Color(255, 255, 255));
        jlApeAdmin.setText("Apellido");
        jPanel2.add(jlApeAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 190, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 860, 30));

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setAutoscrolls(true);

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        getContentPane().add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 860, 580));

        jPanel1.setBackground(new java.awt.Color(13, 71, 161));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Admin");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 140, 20));

        txtCargoAdmin.setBackground(new java.awt.Color(255, 255, 255));
        txtCargoAdmin.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        txtCargoAdmin.setForeground(new java.awt.Color(255, 255, 255));
        txtCargoAdmin.setText("Cargo");
        jPanel1.add(txtCargoAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 140, 20));

        jpPrincipal.setBackground(new java.awt.Color(51, 102, 255));
        jpPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpPrincipalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpPrincipalMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpPrincipalMousePressed(evt);
            }
        });
        jpPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Principal");
        jpPrincipal.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 80, 50));

        jPanel1.add(jpPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 160, 50));

        jpUsuarios.setBackground(new java.awt.Color(0, 102, 204));
        jpUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpUsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpUsuariosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpUsuariosMousePressed(evt);
            }
        });
        jpUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Usuarios");
        jpUsuarios.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 80, 50));

        jPanel1.add(jpUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 160, 50));

        jpreportes.setBackground(new java.awt.Color(0, 102, 204));
        jpreportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpreportesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpreportesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpreportesMousePressed(evt);
            }
        });
        jpreportes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Reportes");
        jpreportes.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 80, 50));

        jPanel1.add(jpreportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 160, 50));

        jpSucursal.setBackground(new java.awt.Color(0, 102, 204));
        jpSucursal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpSucursalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpSucursalMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpSucursalMousePressed(evt);
            }
        });
        jpSucursal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Sucursales");
        jpSucursal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 50));

        jPanel1.add(jpSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 160, 50));

        jpCerrarSesion.setBackground(new java.awt.Color(0, 102, 204));
        jpCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpCerrarSesionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpCerrarSesionMousePressed(evt);
            }
        });
        jpCerrarSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Salir");
        jpCerrarSesion.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 50));

        jPanel1.add(jpCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 160, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jpPrincipalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpPrincipalMousePressed
        // Codigo par mostrar el principal
       principal p1 = new principal();
       p1.setSize(810, 530);
       p1.setLocation(0,0);
        
       content.removeAll();
       content.add(p1, BorderLayout.CENTER);
       content.revalidate();
       content.repaint();
    }//GEN-LAST:event_jpPrincipalMousePressed

    private void jpPrincipalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpPrincipalMouseEntered
        // TODO add your handling code here:[13,71,161]
        jpPrincipal.setBackground(new Color(13, 71, 161));
    }//GEN-LAST:event_jpPrincipalMouseEntered

    private void jpPrincipalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpPrincipalMouseExited
        // TODO add your handling code here:
        jpPrincipal.setBackground(new Color(51,102,255));
    }//GEN-LAST:event_jpPrincipalMouseExited

    private void jbCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCerrarActionPerformed
        //Codigo para cerrar sesion
                          String[] opciones = {"SI","NO"};
          int n = JOptionPane.showOptionDialog(this,"¿Desea Cerrar Sesión?","CONFIRMAR",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,opciones,"");

                    if (n == JOptionPane.YES_OPTION) {
                        //TU CODIGO SI SI
                        Login cerrar = new Login();
                        cerrar.setVisible(true);
                        this.setVisible(false);
                        
                    }else if (n == JOptionPane.NO_OPTION) {
                        //TU CODIGO SI NO
                          JOptionPane.showMessageDialog(null, "Abortando Proceso");
                    }
    }//GEN-LAST:event_jbCerrarActionPerformed

    private void panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMousePressed
        // Para que al precionar el panel se mueva el Jframe
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panelMousePressed

    private void panelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseDragged
        // Codigo para mover el Jframe
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x- xMouse,y - yMouse);
    }//GEN-LAST:event_panelMouseDragged

    private void jpUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpUsuariosMouseEntered
        // TODO add your handling code here:[51,153,255]
      jpUsuarios.setBackground(new Color(51, 153, 255));
    }//GEN-LAST:event_jpUsuariosMouseEntered

    private void jpUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpUsuariosMouseExited
        // TODO add your handling code here:[0,102,204]
      jpUsuarios.setBackground(new Color(0, 102, 204));
    }//GEN-LAST:event_jpUsuariosMouseExited

    private void jpreportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpreportesMouseEntered
        // TODO add your handling code here:
      jpreportes.setBackground(new Color(51, 153, 255));
    }//GEN-LAST:event_jpreportesMouseEntered

    private void jpreportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpreportesMouseExited
        // TODO add your handling code here:
      jpreportes.setBackground(new Color(0, 102, 204));
    }//GEN-LAST:event_jpreportesMouseExited

    private void jpUsuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpUsuariosMousePressed
        // Metodo para ver los usuarios
       usuariosVisual p1 = new usuariosVisual();
       p1.setSize(850, 578);
       p1.setLocation(0,0);
        
       content.removeAll();
       content.add(p1, BorderLayout.CENTER);
       content.revalidate();
       content.repaint();
    }//GEN-LAST:event_jpUsuariosMousePressed

    private void jpSucursalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpSucursalMouseEntered
        // TODO add your handling code here:
       jpSucursal.setBackground(new Color(51, 153, 255));
    }//GEN-LAST:event_jpSucursalMouseEntered

    private void jpSucursalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpSucursalMouseExited
        // TODO add your handling code here:
      jpSucursal.setBackground(new Color(0, 102, 204));
    }//GEN-LAST:event_jpSucursalMouseExited

    private void jpSucursalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpSucursalMousePressed
        //Metodo para ver las sucursales
       sucursalVisual p1 = new sucursalVisual();
       p1.setSize(850, 578);
       p1.setLocation(0,0);
        
       content.removeAll();
       content.add(p1, BorderLayout.CENTER);
       content.revalidate();
       content.repaint();
    }//GEN-LAST:event_jpSucursalMousePressed

    private void jpCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpCerrarSesionMouseEntered
        // TODO add your handling code here:
        jpCerrarSesion.setBackground(new Color(51, 153, 255));
    }//GEN-LAST:event_jpCerrarSesionMouseEntered

    private void jpCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpCerrarSesionMouseExited
        // TODO add your handling code here:
        jpCerrarSesion.setBackground(new Color(0, 102, 204));
    }//GEN-LAST:event_jpCerrarSesionMouseExited

    private void jpCerrarSesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpCerrarSesionMousePressed
        // Regreso al inicio de usuario
        String[] opciones = {"SI","NO"};
        int n = JOptionPane.showOptionDialog(this,"¿Desea Cerrar Sesión?","CONFIRMAR",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,opciones,"");

        if (n == JOptionPane.YES_OPTION) {
            //TU CODIGO SI SI
            Login cerrar = new Login();
            cerrar.setVisible(true);
            this.setVisible(false);

        }else if (n == JOptionPane.NO_OPTION) {
            //TU CODIGO SI NO
            JOptionPane.showMessageDialog(null, "Abortando Proceso");
        }
    }//GEN-LAST:event_jpCerrarSesionMousePressed

    private void jpreportesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpreportesMousePressed
        // Metodo para ver los reportes
       reportesVisual p1 = new reportesVisual();
       p1.setSize(850, 578);
       p1.setLocation(0,0);
        
       content.removeAll();
       content.add(p1, BorderLayout.CENTER);
       content.revalidate();
       content.repaint();
    }//GEN-LAST:event_jpreportesMousePressed
  public void centrarTxt(){
        txtCargoAdmin.setHorizontalAlignment(txtCargoAdmin.CENTER);
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbCerrar;
    public javax.swing.JLabel jlApeAdmin;
    public javax.swing.JLabel jlNomAdmin;
    private javax.swing.JPanel jpCerrarSesion;
    private javax.swing.JPanel jpPrincipal;
    private javax.swing.JPanel jpSucursal;
    private javax.swing.JPanel jpUsuarios;
    private javax.swing.JPanel jpreportes;
    private javax.swing.JPanel panel;
    public javax.swing.JLabel txtCargoAdmin;
    private javax.swing.JLabel txtfecha;
    private javax.swing.JLabel txthora;
    // End of variables declaration//GEN-END:variables
}
