package Visual;

import Clases.Productos;
import Clases.ProductosDao;
import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author david
 */
public class Inventario extends javax.swing.JFrame {
  int xMouse, yMouse;     
    DefaultTableModel modelo = new DefaultTableModel();
    Productos prod = new Productos();
    ProductosDao productos = new ProductosDao();
    /**
     * Creates new form Inventario
     */
    public Inventario() {
        initComponents();
        HoraFecha();
        centratTex();
    }
   public void centratTex(){
        txtCargo.setHorizontalAlignment(txtCargo.CENTER);
        jlSucursal.setHorizontalAlignment(jlSucursal.CENTER);
    }
    public void HoraFecha(){
        // Codigo para la fecha    
        LocalDate now = LocalDate.now();
        int year = now.getYear();
        int dia = now.getDayOfMonth();
        int month = now.getMonthValue();
        String[] meses = {"Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre"
            ,"Octubre","Noviembre","Diciembre"};
        txtfecha.setText("Fecha: "+dia+" de "+meses[month - 1]+" de "+year);
   
    //Codigo para la hora
            DateTimeFormatter formateador = DateTimeFormatter.ofPattern("HH:mm:ss");
        Runnable runnable = new Runnable() {
        @Override
        public void run() {
            while (true) {
                try {
                    Thread.sleep(500);
                    txthora.setText(formateador.format(LocalDateTime.now()));
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        }
    };
    Thread hilo = new Thread(runnable);
    hilo.start(); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jlSucursal = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtCargo = new javax.swing.JLabel();
        jpPrincipal = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jpProductos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jlNumSucursal = new javax.swing.JLabel();
        jpCerrarSesion = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jbCerrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txthora = new javax.swing.JLabel();
        txtfecha = new javax.swing.JLabel();
        jlApellido = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        content2.setBackground(new java.awt.Color(255, 255, 255));
        content2.setAutoscrolls(true);

        javax.swing.GroupLayout content2Layout = new javax.swing.GroupLayout(content2);
        content2.setLayout(content2Layout);
        content2Layout.setHorizontalGroup(
            content2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        content2Layout.setVerticalGroup(
            content2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(13, 71, 161));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlSucursal.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jlSucursal.setForeground(new java.awt.Color(255, 255, 255));
        jlSucursal.setText("Sucursal");
        jPanel1.add(jlSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 160, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 140, 20));

        txtCargo.setBackground(new java.awt.Color(255, 255, 255));
        txtCargo.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        txtCargo.setForeground(new java.awt.Color(255, 255, 255));
        txtCargo.setText("Cargo");
        jPanel1.add(txtCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 140, 20));

        jpPrincipal.setBackground(new java.awt.Color(51, 102, 255));
        jpPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpPrincipalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpPrincipalMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpPrincipalMousePressed(evt);
            }
        });
        jpPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Principal");
        jpPrincipal.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 80, 50));

        jPanel1.add(jpPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 160, 50));

        jpProductos.setBackground(new java.awt.Color(0, 102, 204));
        jpProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpProductosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpProductosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpProductosMousePressed(evt);
            }
        });
        jpProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Productos");
        jpProductos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 50));

        jPanel1.add(jpProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 160, 50));

        jlNumSucursal.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jlNumSucursal.setForeground(new java.awt.Color(13, 71, 161));
        jlNumSucursal.setText("N");
        jPanel1.add(jlNumSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 20, -1));

        jpCerrarSesion.setBackground(new java.awt.Color(0, 102, 204));
        jpCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpCerrarSesionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpCerrarSesionMousePressed(evt);
            }
        });
        jpCerrarSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Salir");
        jpCerrarSesion.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 50));

        jPanel1.add(jpCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 160, -1));

        panel.setBackground(new java.awt.Color(13, 71, 161));
        panel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelMouseDragged(evt);
            }
        });
        panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelMousePressed(evt);
            }
        });
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Usuario");
        panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 60, 30));

        jlNombre.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jlNombre.setForeground(new java.awt.Color(255, 255, 255));
        jlNombre.setText("Nombre");
        panel.add(jlNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 190, 30));

        jbCerrar.setBackground(new java.awt.Color(204, 0, 0));
        jbCerrar.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jbCerrar.setForeground(new java.awt.Color(255, 255, 255));
        jbCerrar.setText("X");
        jbCerrar.setBorder(null);
        jbCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCerrarActionPerformed(evt);
            }
        });
        panel.add(jbCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 30, 30));

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txthora.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        txthora.setForeground(new java.awt.Color(255, 255, 255));
        txthora.setText("Hora");
        jPanel2.add(txthora, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 120, 30));

        txtfecha.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        txtfecha.setForeground(new java.awt.Color(255, 255, 255));
        txtfecha.setText("Fecha:");
        jPanel2.add(txtfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 290, 30));

        jlApellido.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jlApellido.setForeground(new java.awt.Color(255, 255, 255));
        jlApellido.setText("Apellido");
        jPanel2.add(jlApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 190, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(160, 160, 160)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(content2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(content2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jpPrincipalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpPrincipalMouseEntered
        // TODO add your handling code here:[13,71,161]
        jpPrincipal.setBackground(new Color(13, 71, 161));
    }//GEN-LAST:event_jpPrincipalMouseEntered

    private void jpPrincipalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpPrincipalMouseExited
        // TODO add your handling code here:
        jpPrincipal.setBackground(new Color(51,102,255));
    }//GEN-LAST:event_jpPrincipalMouseExited

    private void jpPrincipalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpPrincipalMousePressed
        // TODO add your handling code here:
        principal p1 = new principal();
        p1.setSize(810, 530);
        p1.setLocation(0,0);

        content2.removeAll();
        content2.add(p1, BorderLayout.CENTER);
        content2.revalidate();
        content2.repaint();
    }//GEN-LAST:event_jpPrincipalMousePressed

    private void jpProductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpProductosMouseEntered
        // TODO add your handling code here:
        jpProductos.setBackground(new Color(51, 153, 255));
    }//GEN-LAST:event_jpProductosMouseEntered

    private void jpProductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpProductosMouseExited
        // TODO add your handling code here:
        jpProductos.setBackground(new Color(0, 102, 204));
    }//GEN-LAST:event_jpProductosMouseExited

    private void jpProductosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpProductosMousePressed
        // TODO add your handling code here:
        
        productosVisual p1 = new productosVisual();
        p1.setSize(810, 578);
        p1.setLocation(0,0);
        p1.Cargo.setText(txtCargo.getText());
        p1.jbAgreProdSucu.setEnabled(false); 
        p1.jlNUm.setText(jlNumSucursal.getText());
        int num = Integer.valueOf(jlNumSucursal.getText());
        
        List<Productos> ListarUser = productos.ListarProd(num);
        modelo = (DefaultTableModel) p1.jtProductos.getModel();
        Object[] ob = new Object[7];
        for (int i = 0; i < ListarUser.size(); i++) {
            ob[0] = ListarUser.get(i).getIdProd();
            ob[1] = ListarUser.get(i).getNombreProd();
            ob[2] = ListarUser.get(i).getCategoria();
            ob[3] = ListarUser.get(i).getPrecio();
            ob[4] = ListarUser.get(i).getCantidad();
            ob[5] = ListarUser.get(i).getDescripcion();
            ob[6] = ListarUser.get(i).getSucurorigin();
            modelo.addRow(ob);
        }
        p1.jtProductos.setModel(modelo);
        p1.jtProductos.getColumnModel().getColumn(1).setPreferredWidth(230);
        p1.jtProductos.getColumnModel().getColumn(2).setPreferredWidth(100);
        p1.jtProductos.getColumnModel().getColumn(3).setPreferredWidth(100);
        p1.jtProductos.getColumnModel().getColumn(4).setPreferredWidth(100);
        p1.jtProductos.getColumnModel().getColumn(5).setPreferredWidth(300);
        p1.jtProductos.setRowHeight(25);
        
        content2.removeAll();
        content2.add(p1, BorderLayout.CENTER);
        content2.revalidate();
        content2.repaint();
    }//GEN-LAST:event_jpProductosMousePressed

    private void jpCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpCerrarSesionMouseEntered
        // TODO add your handling code here:
        jpCerrarSesion.setBackground(new Color(51, 153, 255));
    }//GEN-LAST:event_jpCerrarSesionMouseEntered

    private void jpCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpCerrarSesionMouseExited
        // TODO add your handling code here:
        jpCerrarSesion.setBackground(new Color(0, 102, 204));
    }//GEN-LAST:event_jpCerrarSesionMouseExited

    private void jpCerrarSesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpCerrarSesionMousePressed
        // Regreso al inicio de usuario
        String[] opciones = {"SI","NO"};
        int n = JOptionPane.showOptionDialog(this,"¿Desea Cerrar Sesión?","CONFIRMAR",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,opciones,"");

        if (n == JOptionPane.YES_OPTION) {
            //TU CODIGO SI SI
            Login cerrar = new Login();
            cerrar.setVisible(true);
            this.setVisible(false);

        }else if (n == JOptionPane.NO_OPTION) {
            //TU CODIGO SI NO
            JOptionPane.showMessageDialog(null, "Abortando Proceso");
        }
    }//GEN-LAST:event_jpCerrarSesionMousePressed

    private void jbCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCerrarActionPerformed
        // TODO add your handling code here:
        String[] opciones = {"SI","NO"};
        int n = JOptionPane.showOptionDialog(this,"¿Desea Cerrar Sesión?","CONFIRMAR",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,opciones,"");

        if (n == JOptionPane.YES_OPTION) {
            //TU CODIGO SI SI
            Login cerrar = new Login();
            cerrar.setVisible(true);
            this.setVisible(false);

        }else if (n == JOptionPane.NO_OPTION) {
            //TU CODIGO SI NO
            JOptionPane.showMessageDialog(null, "Abortando Proceso");
        }
    }//GEN-LAST:event_jbCerrarActionPerformed

    private void panelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x- xMouse,y - yMouse);
    }//GEN-LAST:event_panelMouseDragged

    private void panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panelMousePressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel content2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbCerrar;
    public javax.swing.JLabel jlApellido;
    public javax.swing.JLabel jlNombre;
    public javax.swing.JLabel jlNumSucursal;
    public javax.swing.JLabel jlSucursal;
    private javax.swing.JPanel jpCerrarSesion;
    private javax.swing.JPanel jpPrincipal;
    private javax.swing.JPanel jpProductos;
    private javax.swing.JPanel panel;
    public javax.swing.JLabel txtCargo;
    private javax.swing.JLabel txtfecha;
    private javax.swing.JLabel txthora;
    // End of variables declaration//GEN-END:variables
}
