package Visual;

import Clases.Productos;
import Clases.ProductosDao;
import static Visual.Inventario.content2;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author david
 */
public class InvenVisual extends javax.swing.JPanel {
    DefaultTableModel modelo = new DefaultTableModel();
    Productos prod = new Productos();
    ProductosDao productos = new ProductosDao();

    /**
     * Creates new form InvenVisual
     */
    public InvenVisual() {
        initComponents();
        mostrarInventario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtInventario = new javax.swing.JTable();
        jbSolicitar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jlInsucu = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Cantidad", "ID Sucursal", "Sucursal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtInventario);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 660, 330));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 700, 370));

        jbSolicitar.setBackground(new java.awt.Color(51, 51, 255));
        jbSolicitar.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jbSolicitar.setForeground(new java.awt.Color(255, 255, 255));
        jbSolicitar.setText("Solicitar");
        jbSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSolicitarActionPerformed(evt);
            }
        });
        add(jbSolicitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Ingresar productos de otra sucursal");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jlInsucu.setForeground(new java.awt.Color(255, 255, 255));
        jlInsucu.setText("Sucu");
        add(jlInsucu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jbSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSolicitarActionPerformed
        // TODO add your handling code here:
    int fila = jtInventario.getSelectedRow();
    String num = jlInsucu.getText();

    if (fila >= 0) { // verifica que haya una fila seleccionada
        Object valor = jtInventario.getValueAt(fila, 3); 
        if (valor instanceof Number) {
            // convierte el valor a String y lo compara con num
            if (String.valueOf(valor).equals(num)) {
                JOptionPane.showMessageDialog(null, "No puedes solicitar porque eres de la misma sucursal.");
            } else {
                    SolicitarVisual p1 = new SolicitarVisual();
                    p1.setSize(810, 530);
                    p1.setLocation(0,0);
                    p1.jlNumSoli.setText(jlInsucu.getText());
                    if (fila >= 0) {
                    Object[] filaselect = {
                    jtInventario.getValueAt(fila, 0)
                };

                    p1.txtCodProd.setText(String.valueOf(filaselect[0]));
                   p1.txtSucursal.setText(String.valueOf(jtInventario.getValueAt(fila, 4)));
                    String cod = p1.txtCodProd.getText();
                
                    prod = productos.BuscarPro(cod);

                            p1.jtNombre.setText(""+ prod.getNombreProd());
                            p1.txtdinero.setText(""+prod.getPrecio());

                    prod = productos.BuscarProd(cod, (int) valor);
                    p1.txtPrecio.setText(""+prod.getCantidad());
                    p1.txtIdSucu.setText(""+ prod.getSucurorigin());
                    

            }
                    content2.removeAll();
                    content2.add(p1, BorderLayout.CENTER);
                    content2.revalidate();
                    content2.repaint();
            }
        } else {
            JOptionPane.showMessageDialog(null, "El valor seleccionado no es un número.");
        }
    } else {
        JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguna fila.");
    }
    }//GEN-LAST:event_jbSolicitarActionPerformed

//Enlistando los datos del inventario
    public void mostrarInventario(){
            List<Productos> ListarProdu = productos.ListarInven();
        modelo = (DefaultTableModel) jtInventario.getModel();
        Object[] ob = new Object[5];
        for (int i = 0; i < ListarProdu.size(); i++) {
            ob[0] = ListarProdu.get(i).getIdProd();
            ob[1] = ListarProdu.get(i).getNombreProd();
            ob[2] = ListarProdu.get(i).getCantidad();
            ob[3] = ListarProdu.get(i).getSucurorigin();
            ob[4] = ListarProdu.get(i).getDescripcion();
            modelo.addRow(ob);
        }
        jtInventario.setModel(modelo);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbSolicitar;
    public javax.swing.JLabel jlInsucu;
    private javax.swing.JTable jtInventario;
    // End of variables declaration//GEN-END:variables
}
