package Visual;

import Clases.Productos;
import Clases.ProductosDao;
import Clases.Sucursal;
import Clases.SucursalDao;
import java.sql.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author david
 */
public class ProdSucuBod extends javax.swing.JPanel {
 //Clases a utilizar   
   Productos prod = new Productos();
    ProductosDao productos = new ProductosDao();
    Sucursal sucu = new Sucursal();
    SucursalDao sucursal = new SucursalDao();
    
    /**
     * Creates new form ProdSucuBod
     */
    public ProdSucuBod() {
        initComponents();
    listarCat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Text3 = new javax.swing.JLabel();
        txtCodProd = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        Text9 = new javax.swing.JLabel();
        Text7 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        txtdinero = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        txtPrecio = new javax.swing.JTextField();
        ap1 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        Text10 = new javax.swing.JLabel();
        txtSucursal = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        Text11 = new javax.swing.JLabel();
        Text5 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jbAgregarInv = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jbLimProd = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jbLimProd1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Ingresos de Productos de Bodega a Sucursal");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        Text3.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        Text3.setForeground(new java.awt.Color(0, 0, 255));
        Text3.setText("Codigo del producto");
        add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        txtCodProd.setEditable(false);
        txtCodProd.setBackground(new java.awt.Color(255, 255, 255));
        txtCodProd.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        txtCodProd.setForeground(new java.awt.Color(0, 0, 0));
        txtCodProd.setBorder(null);
        add(txtCodProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 250, 20));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 250, 20));

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Descripción");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));

        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 320, -1));

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Fecha Ingreso");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, -1, -1));

        jDateChooser1.setForeground(new java.awt.Color(255, 255, 255));
        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        jDateChooser1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 150, -1));

        Text9.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        Text9.setForeground(new java.awt.Color(0, 0, 255));
        Text9.setText("Cantidad Almacenada");
        add(Text9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, -1, -1));

        Text7.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        Text7.setForeground(new java.awt.Color(0, 0, 255));
        Text7.setText("Precio Unitario");
        add(Text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, -1, -1));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 110, 10));

        txtdinero.setEditable(false);
        txtdinero.setBackground(new java.awt.Color(255, 255, 255));
        txtdinero.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        txtdinero.setForeground(new java.awt.Color(0, 0, 0));
        txtdinero.setBorder(null);
        add(txtdinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 290, 80, 30));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Q");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, -1, -1));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 90, 10));

        txtPrecio.setBackground(new java.awt.Color(255, 255, 255));
        txtPrecio.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(0, 0, 0));
        txtPrecio.setBorder(null);
        add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 90, 30));

        ap1.setEditable(false);
        ap1.setBackground(new java.awt.Color(255, 255, 255));
        ap1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        ap1.setForeground(new java.awt.Color(0, 0, 0));
        ap1.setBorder(null);
        add(ap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 160, 30));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 160, 10));

        Text10.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        Text10.setForeground(new java.awt.Color(0, 0, 255));
        Text10.setText("Sucursal");
        add(Text10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        txtSucursal.setEditable(false);
        txtSucursal.setBackground(new java.awt.Color(255, 255, 255));
        txtSucursal.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        txtSucursal.setForeground(new java.awt.Color(0, 0, 0));
        txtSucursal.setBorder(null);
        add(txtSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 170, 30));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 170, 10));

        Text11.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        Text11.setForeground(new java.awt.Color(0, 0, 255));
        Text11.setText("Categoria");
        add(Text11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        Text5.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        Text5.setForeground(new java.awt.Color(0, 0, 255));
        Text5.setText("Nombre");
        add(Text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jtNombre.setEditable(false);
        jtNombre.setBackground(new java.awt.Color(255, 255, 255));
        jtNombre.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jtNombre.setForeground(new java.awt.Color(0, 0, 0));
        jtNombre.setBorder(null);
        add(jtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 250, 20));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 260, 20));

        jbAgregarInv.setBackground(new java.awt.Color(0, 51, 255));
        jbAgregarInv.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jbAgregarInv.setForeground(new java.awt.Color(255, 255, 255));
        jbAgregarInv.setText("Agregar");
        jbAgregarInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarInvActionPerformed(evt);
            }
        });
        add(jbAgregarInv, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 100, 30));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cant");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 110, -1));

        jbLimProd.setBackground(new java.awt.Color(0, 51, 255));
        jbLimProd.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jbLimProd.setForeground(new java.awt.Color(255, 255, 255));
        jbLimProd.setText("Limpiar");
        jbLimProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimProdActionPerformed(evt);
            }
        });
        add(jbLimProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, 100, 30));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 60, -1));

        jbLimProd1.setBackground(new java.awt.Color(0, 51, 255));
        jbLimProd1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jbLimProd1.setForeground(new java.awt.Color(255, 255, 255));
        jbLimProd1.setText("Modificar");
        jbLimProd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimProd1ActionPerformed(evt);
            }
        });
        add(jbLimProd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, 100, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jbAgregarInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarInvActionPerformed
        //Codigo para actualizar el valor de la cantidad de inventario
         if(txtSucursal.getText().equals("") || txtPrecio.getText().equals("") || txtCodProd.getText().equals("") || jDateChooser1.getDate().equals("")){
            JOptionPane.showMessageDialog(null, "Todo los campos son requeridos");
            }else{
                                 String[] opciones = {"SI","NO"};

                    int n = JOptionPane.showOptionDialog(this,"¿Todo Correcto?","AGREGAR",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,opciones,"");

                    if (n == JOptionPane.YES_OPTION) {
                        //TU CODIGO SI SI
                            String dpi = txtCodProd.getText();
                            int nit = Integer.parseInt(String.valueOf(jComboBox1.getSelectedItem()));
                            String nom = txtPrecio.getText();
                            String fecha = ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
                            
                            prod.setIdProd(dpi);
                            prod.setCantidad(Integer.valueOf(nom));
                            prod.setSucurorigin(nit);
                            prod.setFecha(Date.valueOf(fecha));
                            
                            productos.RegistrarInv(prod);
                            JOptionPane.showMessageDialog(null, "Producto Registrado");
                            System.out.println("Agregado");
                    }else if (n == JOptionPane.NO_OPTION) {
                        //TU CODIGO SI NO
                          JOptionPane.showMessageDialog(null, "Registrado Cancelado");
                    }
                    
         }
    }//GEN-LAST:event_jbAgregarInvActionPerformed

    private void jbLimProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimProdActionPerformed
        // TODO add your handling code here:
     limpText();
    }//GEN-LAST:event_jbLimProdActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        //Cogigo para selecionar lo que se precione en el Jcombobox
        int nuevo = Integer.parseInt(String.valueOf(jComboBox1.getSelectedItem()));
        sucu = sucursal.BuscarSucId(nuevo);
        String idT = sucu.getUbicacion();
        txtSucursal.setText(idT);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jbLimProd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimProd1ActionPerformed
        // Metodo para modificar el producto en inventario
         String[] opciones = {"SI","NO"};
        if ("".equals(txtCodProd.getText())) {
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        } else{
            int n = JOptionPane.showOptionDialog(this,"¿Que Desea Hacer?","Modificar",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,opciones,"");

            if (n == JOptionPane.YES_OPTION) {
                if (!"".equals(txtCodProd.getText()) || !"".equals(jtNombre.getText()) || !"".equals(txtDescripcion.getText()) || !"".equals(ap1.getText()) || !"".equals(txtdinero.getText()) || !"".equals(txtPrecio.getText()) ||jDateChooser1.getDate().equals("")) {

                    prod.setSucurorigin(Integer.valueOf(String.valueOf(jComboBox1.getSelectedItem())));
                    prod.setCantidad(Integer.valueOf(txtPrecio.getText()));
                    prod.setFecha(java.sql.Date.valueOf(((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText()));
                    prod.setIdProd(txtCodProd.getText());
                    productos.ModificarProdInv(prod);
                    JOptionPane.showMessageDialog(null, "Producto Modificado");
                    limpText();

                }
            }else if (n == JOptionPane.NO_OPTION) {
                //TU CODIGO SI NO
                System.out.print("Error 400");
                JOptionPane.showMessageDialog(null, "Proceso Cancelado");
            }
        }
    }//GEN-LAST:event_jbLimProd1ActionPerformed
//Metodo para limpiar
    public void limpText(){
        txtCodProd.setText("");
        jtNombre.setText("");
        txtPrecio.setText("");
        txtdinero.setText("");
        txtDescripcion.setText("");
    }
//Metodo para listar las categorias en el JPanel
public void listarCat(){
        jComboBox1.removeAllItems();
        List<Sucursal> listProdu = sucursal.ListarSucu();
        
        for (int i = 0; i < listProdu.size(); i++){
            jComboBox1.addItem(String.valueOf(listProdu.get(i).getIdSucur()));
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text10;
    private javax.swing.JLabel Text11;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text5;
    private javax.swing.JLabel Text7;
    private javax.swing.JLabel Text9;
    public javax.swing.JTextField ap1;
    public javax.swing.JComboBox<String> jComboBox1;
    public com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JButton jbAgregarInv;
    private javax.swing.JButton jbLimProd;
    private javax.swing.JButton jbLimProd1;
    public javax.swing.JTextField jtNombre;
    public javax.swing.JTextField txtCodProd;
    public javax.swing.JTextArea txtDescripcion;
    public javax.swing.JTextField txtPrecio;
    public javax.swing.JTextField txtSucursal;
    public javax.swing.JTextField txtdinero;
    // End of variables declaration//GEN-END:variables
}
