
package Visual;

import Clases.Productos;
import Clases.ProductosDao;
import Clases.Sucursal;
import Clases.SucursalDao;
import java.sql.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author david
 */
public class productosEditVisual extends javax.swing.JPanel {
    
    Productos prod = new Productos();
    ProductosDao productos = new ProductosDao();
    Sucursal sucu = new Sucursal();
    SucursalDao sucursal = new SucursalDao();
    /**
     * Creates new form productosEditVisual
     */
    public productosEditVisual() {
        initComponents();
        listarCat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Text3 = new javax.swing.JLabel();
        Text5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Text10 = new javax.swing.JLabel();
        Text9 = new javax.swing.JLabel();
        Text7 = new javax.swing.JLabel();
        txtCodProd = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jtNombre = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        ap1 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jcCategoria = new javax.swing.JComboBox<>();
        txtPrecio = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        txtdinero = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jbModBod = new javax.swing.JButton();
        jbInserBod = new javax.swing.JButton();
        jbLimProd = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Editar Productos Bodega");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        Text3.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        Text3.setForeground(new java.awt.Color(0, 0, 255));
        Text3.setText("Codigo del producto");
        add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        Text5.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        Text5.setForeground(new java.awt.Color(0, 0, 255));
        Text5.setText("Nombre");
        add(Text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Descripción");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));

        Text10.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        Text10.setForeground(new java.awt.Color(0, 0, 255));
        Text10.setText("Categorias");
        add(Text10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        Text9.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        Text9.setForeground(new java.awt.Color(0, 0, 255));
        Text9.setText("Cantidad Almacenada");
        add(Text9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, -1, -1));

        Text7.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        Text7.setForeground(new java.awt.Color(0, 0, 255));
        Text7.setText("Precio Unitario");
        add(Text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, -1, -1));

        txtCodProd.setBackground(new java.awt.Color(255, 255, 255));
        txtCodProd.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        txtCodProd.setForeground(new java.awt.Color(0, 0, 0));
        txtCodProd.setBorder(null);
        add(txtCodProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 250, 20));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 250, 20));

        jtNombre.setBackground(new java.awt.Color(255, 255, 255));
        jtNombre.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jtNombre.setForeground(new java.awt.Color(0, 0, 0));
        jtNombre.setBorder(null);
        add(jtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 250, 20));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 260, 20));

        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 320, -1));

        ap1.setBackground(new java.awt.Color(255, 255, 255));
        ap1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        ap1.setForeground(new java.awt.Color(0, 0, 0));
        ap1.setBorder(null);
        add(ap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 160, 30));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 160, 10));

        jcCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcCategoriaActionPerformed(evt);
            }
        });
        add(jcCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 170, 30));

        txtPrecio.setBackground(new java.awt.Color(255, 255, 255));
        txtPrecio.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(0, 0, 0));
        txtPrecio.setBorder(null);
        add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 90, 30));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 90, 10));

        txtdinero.setBackground(new java.awt.Color(255, 255, 255));
        txtdinero.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        txtdinero.setForeground(new java.awt.Color(0, 0, 0));
        txtdinero.setBorder(null);
        add(txtdinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 290, 80, 30));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 110, 10));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Q");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, -1, -1));

        jbModBod.setBackground(new java.awt.Color(0, 51, 204));
        jbModBod.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jbModBod.setForeground(new java.awt.Color(255, 255, 255));
        jbModBod.setText("Modificar");
        jbModBod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModBodActionPerformed(evt);
            }
        });
        add(jbModBod, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 110, 30));

        jbInserBod.setBackground(new java.awt.Color(0, 51, 204));
        jbInserBod.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jbInserBod.setForeground(new java.awt.Color(255, 255, 255));
        jbInserBod.setText("Insertar");
        jbInserBod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInserBodActionPerformed(evt);
            }
        });
        add(jbInserBod, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 110, 30));

        jbLimProd.setBackground(new java.awt.Color(0, 51, 255));
        jbLimProd.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jbLimProd.setForeground(new java.awt.Color(255, 255, 255));
        jbLimProd.setText("Limpiar");
        jbLimProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimProdActionPerformed(evt);
            }
        });
        add(jbLimProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 100, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jcCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcCategoriaActionPerformed
        // TODO add your handling code here:
         ap1.setText(jcCategoria.getSelectedItem().toString());

    }//GEN-LAST:event_jcCategoriaActionPerformed

    private void jbInserBodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInserBodActionPerformed
        // Codigo para insertar un producto
     String id = txtCodProd.getText();
        prod = productos.BuscarProdExis(id);
        if (prod.getCantidad() == 1) {
            JOptionPane.showMessageDialog(null, "El codigo del producto ya existe");
        } else {
         if(txtCodProd.getText().equals("") || jtNombre.getText().equals("") || txtDescripcion.getText().equals("") || ap1.getText().equals("") || txtPrecio.getText().equals("") || txtdinero.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Todo los campos son requeridos");
            }else{
                    String[] opciones = {"SI","NO"};

                    int n = JOptionPane.showOptionDialog(this,"¿Todo Correcto?","AGREGAR",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,opciones,"");

                    if (n == JOptionPane.YES_OPTION) {
                        //TU CODIGO SI SI arreglar el agregar
//                            String date = dcn.format(ven);
                            String cod = txtCodProd.getText();
                            String nom = jtNombre.getText();
                            String cat = ap1.getText();
                            String des = txtDescripcion.getText();
                            int cant = Integer.parseInt(txtPrecio.getText());
                            Double din = Double.parseDouble(txtdinero.getText());
                            prod.setIdProd(cod);
                            prod.setNombreProd(nom);
                            prod.setCategoria(cat);
                            prod.setDescripcion(des);
                            prod.setStock(cant);
                            prod.setPrecio(din);
                            productos.RegistrarProductos(prod);
                            JOptionPane.showMessageDialog(null, "Producto Registrado");
                            System.out.println("Agregado");
                            limpText();
                    }else if (n == JOptionPane.NO_OPTION) {
                        //TU CODIGO SI NO
                          JOptionPane.showMessageDialog(null, "Registrado Cancelado");
                        }
                    }
        }                 
     
    }//GEN-LAST:event_jbInserBodActionPerformed

    private void jbModBodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModBodActionPerformed
        // TODO add your handling code here:
                            String[] opciones = {"SI","NO"};
      if ("".equals(txtCodProd.getText())) {
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        } else{
            int n = JOptionPane.showOptionDialog(this,"¿Que Desea Hacer?","Modificar",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,opciones,"");

             if (n == JOptionPane.YES_OPTION) {
             if (!"".equals(txtCodProd.getText()) || !"".equals(jtNombre.getText()) || !"".equals(txtDescripcion.getText()) || !"".equals(ap1.getText()) || !"".equals(txtdinero.getText()) || !"".equals(txtPrecio.getText())) {

                prod.setNombreProd(jtNombre.getText());
                prod.setCategoria(ap1.getText());
                prod.setDescripcion(txtDescripcion.getText());
                prod.setStock(Integer.parseInt(txtPrecio.getText()));
                prod.setPrecio(Double.parseDouble(txtdinero.getText()));
                prod.setIdProd(txtCodProd.getText());
                productos.ModificarProducto(prod);
                JOptionPane.showMessageDialog(null, "Producto Modificado");
                limpText();

            }
             }else if (n == JOptionPane.NO_OPTION) {
             //TU CODIGO SI NO
             System.out.print("Error 400");
            JOptionPane.showMessageDialog(null, "Proceso Cancelado");
        } 
    }
    }//GEN-LAST:event_jbModBodActionPerformed

    private void jbLimProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimProdActionPerformed
        // TODO add your handling code here:}
        limpText();
    }//GEN-LAST:event_jbLimProdActionPerformed
    public void listarCat(){
        jcCategoria.removeAllItems();
        List<Productos> listProdu = productos.ListarCat();
        
        for (int i = 0; i < listProdu.size(); i++){
            jcCategoria.addItem(String.valueOf(listProdu.get(i).getCategoria()));
        }
    }
    public void limpText(){
        txtCodProd.setText("");
        jtNombre.setText("");
        txtPrecio.setText("");
        txtdinero.setText("");
        txtDescripcion.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text10;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text5;
    private javax.swing.JLabel Text7;
    private javax.swing.JLabel Text9;
    public javax.swing.JTextField ap1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JButton jbInserBod;
    private javax.swing.JButton jbLimProd;
    private javax.swing.JButton jbModBod;
    public javax.swing.JComboBox<String> jcCategoria;
    public javax.swing.JTextField jtNombre;
    public javax.swing.JTextField txtCodProd;
    public javax.swing.JTextArea txtDescripcion;
    public javax.swing.JTextField txtPrecio;
    public javax.swing.JTextField txtdinero;
    // End of variables declaration//GEN-END:variables
}
