package Visual;

import Clases.ReportesDao;
import Clases.Ventas;
import static Visual.Inicio.content;
import Clases.VentasDao;
import java.awt.BorderLayout;
import java.awt.Component;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author david
 */
public class reportesVisual extends javax.swing.JPanel {
  Ventas sal = new Ventas();
  VentasDao sales = new VentasDao();
  ReportesDao reportes = new ReportesDao();
  DefaultTableModel modelo = new DefaultTableModel();
        DefaultTableModel m;
        static double total;
        double sumatoria;
    /**
     * Creates new form reportesVisual
     */
    public reportesVisual() {
        initComponents();
        listarVentas();
        RowTable();
        cantTable();
        sumaTotal();
        centrar();
        
    }

    public void centrar(){
         jtTotaldia.setHorizontalAlignment(jtTotaldia.CENTER);
        jtCanVent.setHorizontalAlignment(jtCanVent.CENTER);
        jtTitulo.setHorizontalAlignment(jtTitulo.CENTER);
        jlSucurTitle.setHorizontalAlignment(jlSucurTitle.CENTER);
        jtEmpTitle.setHorizontalAlignment(jtEmpTitle.CENTER);
        jlConTitle.setHorizontalAlignment(jlConTitle.CENTER);
        jlCons.setHorizontalAlignment(jlCons.CENTER);
    }
        public void RowTable(){
    jtVentasReal.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
    jtVentasReal.setRowHeight(20);
    for (int column = 0; column < jtVentasReal.getColumnCount(); column++) {
        TableColumn tableColumn = jtVentasReal.getColumnModel().getColumn(column);
        int preferredWidth = tableColumn.getMinWidth();
        int maxWidth = tableColumn.getMaxWidth();

        for (int row = 0; row < jtVentasReal.getRowCount(); row++) {
            TableCellRenderer cellRenderer = jtVentasReal.getCellRenderer(row, column);
            Component c = jtVentasReal.prepareRenderer(cellRenderer, row, column);
            int width = c.getPreferredSize().width + jtVentasReal.getIntercellSpacing().width;
            preferredWidth = Math.max(preferredWidth, width);

            //  Hemos excedido el ancho máximo, no es necesario verificar otras filas
            if (preferredWidth >= maxWidth) {
                preferredWidth = maxWidth;
                break;
            }
        }
        tableColumn.setPreferredWidth(preferredWidth);
    }
    }
        
public void sumaTotal(){
 double sumatoria1 = 0.0;
DecimalFormat df = new DecimalFormat("#.##");
int totalRow = jtVentasReal.getRowCount();
totalRow -= 1;
for(int i=0; i <= totalRow; i++) {
    sumatoria = Double.parseDouble(String.valueOf(jtVentasReal.getValueAt(i,6)));
    sumatoria1 += sumatoria;
}

Double totalForm = Double.parseDouble(df.format(sumatoria1));
jtTotaldia.setText(String.valueOf(totalForm));
     
}
    
    public void cantTable(){
        int cant = jtVentasReal.getRowCount();
        jtCanVent.setText(String.valueOf(cant));
    }   
    
    public void listarVentas(){
        List<Ventas> ListarUser = reportes.ListRVent();
        modelo = (DefaultTableModel) jtVentasReal.getModel();
        Object[] ob = new Object[7];
        for (int i = 0; i < ListarUser.size(); i++) {
            ob[0] = ListarUser.get(i).getIdVenta();
            ob[1] = ListarUser.get(i).getNomUser()+" "+ ListarUser.get(i).getApeUser();
            ob[2] = ListarUser.get(i).getNomClie()+" "+ ListarUser.get(i).getApelClie();
            ob[3] = ListarUser.get(i).getUbiSucur();
            ob[4] = ListarUser.get(i).getFecha();
            ob[5] = ListarUser.get(i).getTotal();
            ob[6] = ListarUser.get(i).getSubtotal();
            modelo.addRow(ob);
        }
        jtVentasReal.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbRepProd = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jtTitulo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtProdMas = new javax.swing.JTable();
        jbReportIngresos = new javax.swing.JButton();
        jbReportCantidad = new javax.swing.JButton();
        jbRepSucu = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtRepSucur = new javax.swing.JTable();
        jlSucurTitle = new javax.swing.JLabel();
        jbRepSucIngre = new javax.swing.JButton();
        jbRepCantSucu = new javax.swing.JButton();
        jdRepEmpleado = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jtEmpTitle = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtRepEmp = new javax.swing.JTable();
        jbEmpCanti = new javax.swing.JButton();
        jbEmpIngres = new javax.swing.JButton();
        jdRepCom = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jlConTitle = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtConsutas = new javax.swing.JTable();
        jbConCant = new javax.swing.JButton();
        jbConIngre = new javax.swing.JButton();
        jdRepCli = new javax.swing.JDialog();
        jPanel10 = new javax.swing.JPanel();
        jlCons = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jtRepCli = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtVentasReal = new javax.swing.JTable();
        jtCanVent = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtTotaldia = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jbProdRepor = new javax.swing.JButton();
        jbReporSucursal = new javax.swing.JButton();
        jbRepEmpleados = new javax.swing.JButton();
        jbConsultas = new javax.swing.JButton();
        jbRepCli = new javax.swing.JButton();

        jbRepProd.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtTitulo.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jtTitulo.setForeground(new java.awt.Color(0, 51, 255));
        jtTitulo.setText("Productos");
        jPanel2.add(jtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 20, 480, -1));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtProdMas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Producto", "Total Vendido"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtProdMas);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 600, 270));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 620, 300));

        jbReportIngresos.setBackground(new java.awt.Color(0, 102, 204));
        jbReportIngresos.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jbReportIngresos.setForeground(new java.awt.Color(255, 255, 255));
        jbReportIngresos.setText("Por Ingresos");
        jbReportIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbReportIngresosActionPerformed(evt);
            }
        });
        jPanel2.add(jbReportIngresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jbReportCantidad.setBackground(new java.awt.Color(0, 102, 204));
        jbReportCantidad.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jbReportCantidad.setForeground(new java.awt.Color(255, 255, 255));
        jbReportCantidad.setText("Por Cantidad");
        jbReportCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbReportCantidadActionPerformed(evt);
            }
        });
        jPanel2.add(jbReportCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        jbRepProd.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 460));

        jbRepSucu.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtRepSucur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Sucursal", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jtRepSucur);

        jPanel5.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 600, 240));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 630, 270));

        jlSucurTitle.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jlSucurTitle.setForeground(new java.awt.Color(0, 51, 255));
        jlSucurTitle.setText("Sucursal");
        jPanel4.add(jlSucurTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 620, -1));

        jbRepSucIngre.setBackground(new java.awt.Color(0, 102, 204));
        jbRepSucIngre.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jbRepSucIngre.setForeground(new java.awt.Color(255, 255, 255));
        jbRepSucIngre.setText("Por Ingresos");
        jbRepSucIngre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRepSucIngreActionPerformed(evt);
            }
        });
        jPanel4.add(jbRepSucIngre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jbRepCantSucu.setBackground(new java.awt.Color(0, 102, 204));
        jbRepCantSucu.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jbRepCantSucu.setForeground(new java.awt.Color(255, 255, 255));
        jbRepCantSucu.setText("Por Cantidad");
        jbRepCantSucu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRepCantSucuActionPerformed(evt);
            }
        });
        jPanel4.add(jbRepCantSucu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        jbRepSucu.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 440));

        jdRepEmpleado.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtEmpTitle.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jtEmpTitle.setForeground(new java.awt.Color(0, 51, 255));
        jtEmpTitle.setText("Empleados");
        jPanel6.add(jtEmpTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 20, 620, -1));

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtRepEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DPI", "Usuario", "Total", "Ubicacion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jtRepEmp);

        jPanel7.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 17, 670, 280));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 690, 310));

        jbEmpCanti.setBackground(new java.awt.Color(0, 153, 204));
        jbEmpCanti.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jbEmpCanti.setForeground(new java.awt.Color(255, 255, 255));
        jbEmpCanti.setText("Por Cantidad");
        jbEmpCanti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEmpCantiActionPerformed(evt);
            }
        });
        jPanel6.add(jbEmpCanti, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jbEmpIngres.setBackground(new java.awt.Color(0, 153, 204));
        jbEmpIngres.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jbEmpIngres.setForeground(new java.awt.Color(255, 255, 255));
        jbEmpIngres.setText("Por ingreso");
        jbEmpIngres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEmpIngresActionPerformed(evt);
            }
        });
        jPanel6.add(jbEmpIngres, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        jdRepEmpleado.getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 460));

        jdRepCom.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlConTitle.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jlConTitle.setForeground(new java.awt.Color(0, 51, 255));
        jlConTitle.setText("Consultas");
        jPanel8.add(jlConTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 700, -1));

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));

        jtConsutas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ubicacion", "ID", "Producto", "Total"
            }
        ));
        jScrollPane5.setViewportView(jtConsutas);
        if (jtConsutas.getColumnModel().getColumnCount() > 0) {
            jtConsutas.getColumnModel().getColumn(1).setMaxWidth(100);
        }

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 710, 340));

        jbConCant.setBackground(new java.awt.Color(0, 153, 204));
        jbConCant.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jbConCant.setForeground(new java.awt.Color(255, 255, 255));
        jbConCant.setText("Por cantidad");
        jbConCant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConCantActionPerformed(evt);
            }
        });
        jPanel8.add(jbConCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jbConIngre.setBackground(new java.awt.Color(0, 153, 204));
        jbConIngre.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jbConIngre.setForeground(new java.awt.Color(255, 255, 255));
        jbConIngre.setText("Por ingreso");
        jbConIngre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConIngreActionPerformed(evt);
            }
        });
        jPanel8.add(jbConIngre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        jdRepCom.getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 470));

        jdRepCli.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlCons.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jlCons.setForeground(new java.awt.Color(0, 51, 255));
        jlCons.setText("Consultas");
        jPanel10.add(jlCons, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 640, -1));

        jPanel11.setBackground(new java.awt.Color(204, 204, 204));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtRepCli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DPI", "Cliente", "Ganancias"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jtRepCli);

        jPanel11.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 610, 300));

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 630, 320));

        jdRepCli.getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 410));

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("Reportes");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtVentasReal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Usuario", "Cliente", "Sucursal", "Fecha", "Subtotal", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtVentasReal);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 770, 400));

        jtCanVent.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jtCanVent.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jtCanVent, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 110, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 110, 10));

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 1, 17)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 204));
        jLabel8.setText("Ventas");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, -1, 40));

        jLabel12.setFont(new java.awt.Font("Liberation Sans", 1, 17)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 204));
        jLabel12.setText("Total");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, -1, 40));

        jtTotaldia.setEditable(false);
        jtTotaldia.setBackground(new java.awt.Color(204, 204, 204));
        jtTotaldia.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jtTotaldia.setForeground(new java.awt.Color(0, 0, 0));
        jtTotaldia.setBorder(null);
        jPanel1.add(jtTotaldia, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, 150, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 450, 150, 10));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 800, 460));

        jbProdRepor.setBackground(new java.awt.Color(0, 51, 153));
        jbProdRepor.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jbProdRepor.setForeground(new java.awt.Color(255, 255, 255));
        jbProdRepor.setText("Productos");
        jbProdRepor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProdReporActionPerformed(evt);
            }
        });
        add(jbProdRepor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jbReporSucursal.setBackground(new java.awt.Color(0, 51, 153));
        jbReporSucursal.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jbReporSucursal.setForeground(new java.awt.Color(255, 255, 255));
        jbReporSucursal.setText("Sucursal");
        jbReporSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbReporSucursalActionPerformed(evt);
            }
        });
        add(jbReporSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        jbRepEmpleados.setBackground(new java.awt.Color(0, 51, 153));
        jbRepEmpleados.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jbRepEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        jbRepEmpleados.setText("Empleados");
        jbRepEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRepEmpleadosActionPerformed(evt);
            }
        });
        add(jbRepEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        jbConsultas.setBackground(new java.awt.Color(0, 51, 153));
        jbConsultas.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jbConsultas.setForeground(new java.awt.Color(255, 255, 255));
        jbConsultas.setText("Consultas");
        jbConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultasActionPerformed(evt);
            }
        });
        add(jbConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 120, -1));

        jbRepCli.setBackground(new java.awt.Color(0, 51, 153));
        jbRepCli.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jbRepCli.setForeground(new java.awt.Color(255, 255, 255));
        jbRepCli.setText("Clientes");
        jbRepCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRepCliActionPerformed(evt);
            }
        });
        add(jbRepCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbProdReporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProdReporActionPerformed
        // TODO add your handling code here:
    limpRank();
    TenMoreSales();
    jbRepProd.setSize(680, 470);//Asignas tamaño (x,y)
    jbRepProd.setLocationRelativeTo(null);//posicion
    jbRepProd.setModal(true);//que se ubique al centro
    jbRepProd.setVisible(true);//que se haga visible
    jbRepProd.setDefaultCloseOperation(jbRepProd.HIDE_ON_CLOSE);
    }//GEN-LAST:event_jbProdReporActionPerformed

    private void jbReportIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbReportIngresosActionPerformed
        // TODO add your handling code here:
        limpRank();
        TenMoreIngre();
    }//GEN-LAST:event_jbReportIngresosActionPerformed

    private void jbReportCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbReportCantidadActionPerformed
        // TODO add your handling code here:
        limpRank();
        TenMoreSales();
    }//GEN-LAST:event_jbReportCantidadActionPerformed

    private void jbReporSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbReporSucursalActionPerformed
        // TODO add your handling code here:
    limpRankSuc();
    TreMoreIngre();    
    jbRepSucu.setSize(680, 450);//Asignas tamaño (x,y)
    jbRepSucu.setLocationRelativeTo(null);//posicion
    jbRepSucu.setModal(true);//que se ubique al centro
    jbRepSucu.setVisible(true);//que se haga visible
    jbRepSucu.setDefaultCloseOperation(jbRepProd.HIDE_ON_CLOSE);
    }//GEN-LAST:event_jbReporSucursalActionPerformed

    private void jbRepSucIngreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRepSucIngreActionPerformed
        // TODO add your handling code here:
        limpRankSuc();   
        TreMoreCant();
    }//GEN-LAST:event_jbRepSucIngreActionPerformed

    private void jbRepCantSucuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRepCantSucuActionPerformed
        // TODO add your handling code here:
        limpRankSuc();
        TreMoreIngre(); 
    }//GEN-LAST:event_jbRepCantSucuActionPerformed

    private void jbRepEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRepEmpleadosActionPerformed
        // TODO add your handling code here:
    limpRankEmp();
    TreMoreInEmp();    
    jdRepEmpleado.setSize(720, 475);//Asignas tamaño (x,y)
    jdRepEmpleado.setLocationRelativeTo(null);//posicion
    jdRepEmpleado.setModal(true);//que se ubique al centro
    jdRepEmpleado.setVisible(true);//que se haga visible
    jdRepEmpleado.setDefaultCloseOperation(jbRepProd.HIDE_ON_CLOSE);
    }//GEN-LAST:event_jbRepEmpleadosActionPerformed

    private void jbEmpCantiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEmpCantiActionPerformed
        // TODO add your handling code here:
    limpRankEmp();
    TreMoreCantEmp();    
    }//GEN-LAST:event_jbEmpCantiActionPerformed

    private void jbEmpIngresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEmpIngresActionPerformed
        // TODO add your handling code here:
    limpRankEmp();
    TreMoreInEmp(); 
    }//GEN-LAST:event_jbEmpIngresActionPerformed

    private void jbConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultasActionPerformed
        // TODO add your handling code here:
    limpRankCon();    
    FiveCant();    
    jdRepCom.setSize(740, 480);//Asignas tamaño (x,y)
    jdRepCom.setLocationRelativeTo(null);//posicion
    jdRepCom.setModal(true);//que se ubique al centro
    jdRepCom.setVisible(true);//que se haga visible
    jdRepCom.setDefaultCloseOperation(jbRepProd.HIDE_ON_CLOSE);
    }//GEN-LAST:event_jbConsultasActionPerformed

    private void jbConIngreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConIngreActionPerformed
        // TODO add your handling code here:
        limpRankCon(); 
        FiveIngre();
    }//GEN-LAST:event_jbConIngreActionPerformed

    private void jbConCantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConCantActionPerformed
        // TODO add your handling code here:
      limpRankCon();    
      FiveCant();    
    }//GEN-LAST:event_jbConCantActionPerformed

    private void jbRepCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRepCliActionPerformed
        // TODO add your handling code here:
    limpRankClie();
    TenIngreCli();    
    jdRepCli.setSize(680, 430);//Asignas tamaño (x,y)
    jdRepCli.setLocationRelativeTo(null);//posicion
    jdRepCli.setModal(true);//que se ubique al centro
    jdRepCli.setVisible(true);//que se haga visible
    jdRepCli.setDefaultCloseOperation(jbRepProd.HIDE_ON_CLOSE);
    }//GEN-LAST:event_jbRepCliActionPerformed

    public void TenMoreSales(){
         List<Ventas> ListarUser = reportes.LisTenProd();
        modelo = (DefaultTableModel) jtProdMas.getModel();
        Object[] ob = new Object[7];
        for (int i = 0; i < ListarUser.size(); i++) {
            ob[0] = ListarUser.get(i).getNomUser();
            ob[1] = ListarUser.get(i).getApeUser();
            ob[2] = ListarUser.get(i).getTotal();
            modelo.addRow(ob);
        }
        jtProdMas.setModel(modelo);
        jtTitulo.setText("Top 10 productos más Vendidos");
    }
    public void TenMoreIngre(){
         List<Ventas> ListarUser = reportes.LisTenProdMas();
        modelo = (DefaultTableModel) jtProdMas.getModel();
        Object[] ob = new Object[7];
        for (int i = 0; i < ListarUser.size(); i++) {
            ob[0] = ListarUser.get(i).getNomUser();
            ob[1] = ListarUser.get(i).getApeUser();
            ob[2] = ListarUser.get(i).getTotal();
            modelo.addRow(ob);
        }
        jtProdMas.setModel(modelo);
        jtTitulo.setText("Top 10 productos con más Ingresos");
    }

    public void TreMoreIngre(){
         List<Ventas> ListarUser = reportes.LisTreMas();
        modelo = (DefaultTableModel) jtRepSucur.getModel();
        Object[] ob = new Object[7];
        for (int i = 0; i < ListarUser.size(); i++) {
            ob[0] = ListarUser.get(i).getSucursid();
            ob[1] = ListarUser.get(i).getUbiSucur();
            ob[2] = ListarUser.get(i).getTotal();
            modelo.addRow(ob);
        }
        jtRepSucur.setModel(modelo);
        jlSucurTitle.setText("Top 3 sucursales con más ingresos");
    }
   
    public void TreMoreCant(){
         List<Ventas> ListarUser = reportes.LisCanTreMas();
        modelo = (DefaultTableModel) jtRepSucur.getModel();
        Object[] ob = new Object[3];
        for (int i = 0; i < ListarUser.size(); i++) {
            ob[0] = ListarUser.get(i).getSucursid();
            ob[1] = ListarUser.get(i).getUbiSucur();
            ob[2] = ListarUser.get(i).getTotal();
            modelo.addRow(ob);
        }
        jtRepSucur.setModel(modelo);
        jlSucurTitle.setText("Top 3 sucursales con más ventas");
    }
    
        public void TreMoreInEmp(){
         List<Ventas> ListarUser = reportes.LisImEmp();
        modelo = (DefaultTableModel) jtRepEmp.getModel();
        Object[] ob = new Object[4];
        for (int i = 0; i < ListarUser.size(); i++) {
            ob[0] = ListarUser.get(i).getDpiUser();
            ob[1] = ListarUser.get(i).getNomUser() +" "+ ListarUser.get(i).getApeUser();
            ob[2] = ListarUser.get(i).getTotal();
            ob[3] = ListarUser.get(i).getUbiSucur();
            modelo.addRow(ob);
        }
        jtRepEmp.setModel(modelo);
        jtEmpTitle.setText("Top 3 Empleados con más Ingresos");
    }
     
    public void TreMoreCantEmp(){
         List<Ventas> ListarUser = reportes.LisCantEmp();
        modelo = (DefaultTableModel) jtRepEmp.getModel();
        Object[] ob = new Object[4];
        for (int i = 0; i < ListarUser.size(); i++) {
            ob[0] = ListarUser.get(i).getDpiUser();
            ob[1] = ListarUser.get(i).getNomUser() +" "+ ListarUser.get(i).getApeUser();
            ob[2] = ListarUser.get(i).getTotal();
            ob[3] = ListarUser.get(i).getUbiSucur();
            modelo.addRow(ob);
        }
        jtRepEmp.setModel(modelo);
        jtEmpTitle.setText("Top 3 Empleados con más Ventas");
    }

    public void FiveCant(){
         List<Ventas> ListarUser = reportes.LisCantCon();
        modelo = (DefaultTableModel) jtConsutas.getModel();
        Object[] ob = new Object[4];
        for (int i = 0; i < ListarUser.size(); i++) {
            ob[0] = ListarUser.get(i).getUbiSucur();
            ob[1] = ListarUser.get(i).getDpiUser();
            ob[2] = ListarUser.get(i).getNomUser();
            ob[3] = ListarUser.get(i).getTotal();
            modelo.addRow(ob);
        }
        jtConsutas.setModel(modelo);
        jlConTitle.setText("Top 5 productos más vendidos por sucursal");
    }     
    
        public void FiveIngre(){
         List<Ventas> ListarUser = reportes.LisIngreCon();
        modelo = (DefaultTableModel) jtConsutas.getModel();
        Object[] ob = new Object[4];
        for (int i = 0; i < ListarUser.size(); i++) {
            ob[0] = ListarUser.get(i).getUbiSucur();
            ob[1] = ListarUser.get(i).getDpiUser();
            ob[2] = ListarUser.get(i).getNomUser();
            ob[3] = ListarUser.get(i).getTotal();
            modelo.addRow(ob);
        }
        jtConsutas.setModel(modelo);
        jlConTitle.setText("Top 5 productos con más ingresos por sucursal");
    }        
        
     public void TenIngreCli(){
         List<Ventas> ListarUser = reportes.LisCliente();
        modelo = (DefaultTableModel) jtRepCli.getModel();
        Object[] ob = new Object[3];
        for (int i = 0; i < ListarUser.size(); i++) {
            ob[0] = ListarUser.get(i).getDpiUser();
            ob[1] = ListarUser.get(i).getNomClie() +" "+ListarUser.get(i).getApelClie();
            ob[2] = ListarUser.get(i).getTotal();
            modelo.addRow(ob);
        }
        jtRepCli.setModel(modelo);
        jlCons.setText("Top 10 de clientes que más ganancias generan");
    }          

    public void limpRank(){
    DefaultTableModel temp = (DefaultTableModel) jtProdMas.getModel();
    int filas = jtProdMas.getRowCount();

    for (int a = 0; filas > a; a++) {
        temp.removeRow(0);
    }
}
public void limpRankSuc(){
    DefaultTableModel temp = (DefaultTableModel) jtRepSucur.getModel();
    int filas = jtRepSucur.getRowCount();

    for (int a = 0; filas > a; a++) {
        temp.removeRow(0);
    }
}
public void limpRankEmp(){
    DefaultTableModel temp = (DefaultTableModel) jtRepEmp.getModel();
    int filas = jtRepEmp.getRowCount();

    for (int a = 0; filas > a; a++) {
        temp.removeRow(0);
    }
}

public void limpRankCon(){
    DefaultTableModel temp = (DefaultTableModel) jtConsutas.getModel();
    int filas = jtConsutas.getRowCount();

    for (int a = 0; filas > a; a++) {
        temp.removeRow(0);
    }
}

public void limpRankClie(){
    DefaultTableModel temp = (DefaultTableModel) jtRepCli.getModel();
    int filas = jtRepCli.getRowCount();

    for (int a = 0; filas > a; a++) {
        temp.removeRow(0);
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbConCant;
    private javax.swing.JButton jbConIngre;
    private javax.swing.JButton jbConsultas;
    private javax.swing.JButton jbEmpCanti;
    private javax.swing.JButton jbEmpIngres;
    private javax.swing.JButton jbProdRepor;
    private javax.swing.JButton jbRepCantSucu;
    private javax.swing.JButton jbRepCli;
    private javax.swing.JButton jbRepEmpleados;
    private javax.swing.JDialog jbRepProd;
    private javax.swing.JButton jbRepSucIngre;
    private javax.swing.JDialog jbRepSucu;
    private javax.swing.JButton jbReporSucursal;
    private javax.swing.JButton jbReportCantidad;
    private javax.swing.JButton jbReportIngresos;
    private javax.swing.JDialog jdRepCli;
    private javax.swing.JDialog jdRepCom;
    private javax.swing.JDialog jdRepEmpleado;
    private javax.swing.JLabel jlConTitle;
    private javax.swing.JLabel jlCons;
    private javax.swing.JLabel jlSucurTitle;
    private javax.swing.JLabel jtCanVent;
    private javax.swing.JTable jtConsutas;
    private javax.swing.JLabel jtEmpTitle;
    private javax.swing.JTable jtProdMas;
    private javax.swing.JTable jtRepCli;
    private javax.swing.JTable jtRepEmp;
    private javax.swing.JTable jtRepSucur;
    private javax.swing.JLabel jtTitulo;
    private javax.swing.JTextField jtTotaldia;
    private javax.swing.JTable jtVentasReal;
    // End of variables declaration//GEN-END:variables
}
