package Visual;

import Clases.Solicitud;
import Clases.SolicitudDao;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author david
 */
public class SolicitarVisual extends javax.swing.JPanel {
//Llamomos a las clases que necesitaremos
        Solicitud sol = new Solicitud();
        SolicitudDao solicitud = new SolicitudDao();
    /**
     * Creates new form SolicitarVisual
     */
    public SolicitarVisual() {
        initComponents();
        mostrarFecha();
    }
//Metodo para mostrar la fecha en el JDateChoose
    public void mostrarFecha(){
            LocalDate now = LocalDate.now();
            int year = now.getYear();
            int dia = now.getDayOfMonth();
            int month = now.getMonthValue();
            String[] meses = {"01","02","03","04","05","06","07","08","09"
                ,"10","11","12"};
     try {
          String fecha = year+"-"+meses[month - 1]+"-"+dia;
          SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
          Date fechaDate = formato.parse(fecha);
          jdFechaSol.setDate(fechaDate);
          } catch (ParseException ex) {
            Logger.getLogger(ventasVisual.class.getName()).log(Level.SEVERE, null, ex);
          }      
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Text3 = new javax.swing.JLabel();
        txtCodProd = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Text5 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txtSucursal = new javax.swing.JTextField();
        Text10 = new javax.swing.JLabel();
        Text9 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        Text7 = new javax.swing.JLabel();
        txtdinero = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        txtCanSoli = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        Text11 = new javax.swing.JLabel();
        jbEnviar = new javax.swing.JButton();
        txtIdSucu = new javax.swing.JTextField();
        jdFechaSol = new com.toedter.calendar.JDateChooser();
        Text12 = new javax.swing.JLabel();
        Text13 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jlNumSoli = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Solicitar Productos");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        Text3.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        Text3.setForeground(new java.awt.Color(0, 0, 255));
        Text3.setText("Codigo del producto");
        add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        txtCodProd.setEditable(false);
        txtCodProd.setBackground(new java.awt.Color(255, 255, 255));
        txtCodProd.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        txtCodProd.setForeground(new java.awt.Color(0, 0, 0));
        txtCodProd.setBorder(null);
        add(txtCodProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 250, 20));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 250, 20));

        Text5.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        Text5.setForeground(new java.awt.Color(0, 0, 255));
        Text5.setText("Nombre");
        add(Text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jtNombre.setEditable(false);
        jtNombre.setBackground(new java.awt.Color(255, 255, 255));
        jtNombre.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jtNombre.setForeground(new java.awt.Color(0, 0, 0));
        jtNombre.setBorder(null);
        add(jtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 250, 20));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 260, 20));

        txtSucursal.setEditable(false);
        txtSucursal.setBackground(new java.awt.Color(255, 255, 255));
        txtSucursal.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        txtSucursal.setForeground(new java.awt.Color(0, 0, 0));
        txtSucursal.setBorder(null);
        add(txtSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 180, 30));

        Text10.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        Text10.setForeground(new java.awt.Color(0, 0, 255));
        Text10.setText("Sucursal Origen");
        add(Text10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        Text9.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        Text9.setForeground(new java.awt.Color(0, 0, 255));
        Text9.setText("Fecha");
        add(Text9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, -1, -1));

        txtPrecio.setEditable(false);
        txtPrecio.setBackground(new java.awt.Color(255, 255, 255));
        txtPrecio.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(0, 0, 0));
        txtPrecio.setBorder(null);
        add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 90, 30));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 90, 10));

        Text7.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        Text7.setForeground(new java.awt.Color(0, 0, 255));
        Text7.setText("Precio Unitario");
        add(Text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, -1, -1));

        txtdinero.setEditable(false);
        txtdinero.setBackground(new java.awt.Color(255, 255, 255));
        txtdinero.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        txtdinero.setForeground(new java.awt.Color(0, 0, 0));
        txtdinero.setBorder(null);
        add(txtdinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 80, 30));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Q");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, -1, -1));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 110, 10));

        txtCanSoli.setBackground(new java.awt.Color(255, 255, 255));
        txtCanSoli.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        txtCanSoli.setForeground(new java.awt.Color(0, 0, 0));
        txtCanSoli.setBorder(null);
        add(txtCanSoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 90, 30));
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 90, 10));

        Text11.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        Text11.setForeground(new java.awt.Color(0, 0, 255));
        Text11.setText("Cantidad Almacenada");
        add(Text11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        jbEnviar.setBackground(new java.awt.Color(0, 51, 255));
        jbEnviar.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jbEnviar.setForeground(new java.awt.Color(255, 255, 255));
        jbEnviar.setText("Solicitar");
        jbEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEnviarActionPerformed(evt);
            }
        });
        add(jbEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, -1, -1));

        txtIdSucu.setEditable(false);
        txtIdSucu.setBackground(new java.awt.Color(255, 255, 255));
        txtIdSucu.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        txtIdSucu.setForeground(new java.awt.Color(0, 0, 0));
        txtIdSucu.setBorder(null);
        txtIdSucu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdSucuActionPerformed(evt);
            }
        });
        add(txtIdSucu, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 30, 30));

        jdFechaSol.setDateFormatString("yyyy-MM-dd");
        jdFechaSol.setEnabled(false);
        add(jdFechaSol, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 150, -1));

        Text12.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        Text12.setForeground(new java.awt.Color(0, 0, 255));
        Text12.setText("Cantidad Solicitada");
        add(Text12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, -1));

        Text13.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        Text13.setForeground(new java.awt.Color(0, 0, 255));
        Text13.setText("Sucursal");
        add(Text13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));
        add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 180, 10));

        jlNumSoli.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jlNumSoli.setForeground(new java.awt.Color(0, 0, 0));
        jlNumSoli.setText("Num");
        add(jlNumSoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jbEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEnviarActionPerformed
        // TODO add your handling code here:
                if(txtCanSoli.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Necesita ingresar la cantidad deseada");
            }else{
                    String[] opciones = {"SI","NO"};

                    int n = JOptionPane.showOptionDialog(this,"¿Todo Correcto?","AGREGAR",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,opciones,"");

                    if (n == JOptionPane.YES_OPTION) {
                        //TU CODIGO SI SI
                            String idProd = txtCodProd.getText();
                            int canSoli = Integer.valueOf(txtCanSoli.getText());
                            int sucSoli = Integer.valueOf(txtIdSucu.getText());
                            int sucOrig = Integer.valueOf(jlNumSoli.getText());
                            String fechVent = ((JTextField)jdFechaSol.getDateEditor().getUiComponent()).getText();
                            String estado = "Enviado";
                            
                            sol.setSoliProd(idProd);
                            sol.setSoliSucuId(sucSoli);
                            sol.setSoliFecha(java.sql.Date.valueOf(fechVent));
                            sol.setSoliCant(canSoli);
                            sol.setEstado(estado);
                            sol.setSoliSucuOrigen(sucOrig);
                            
                            solicitud.RegistrarVenta(sol);
                           JOptionPane.showMessageDialog(null, "Solicitud Registrado");
                           limpiar();
                            System.out.println("Agregado");
                    }else if (n == JOptionPane.NO_OPTION) {
                        //TU CODIGO SI NO
                          JOptionPane.showMessageDialog(null, "Solicitud Cancelada");
                    }
                    
         }
    }//GEN-LAST:event_jbEnviarActionPerformed
    public void limpiar(){
        txtCodProd.setText("");
        jtNombre.setText("");
        txtPrecio.setText("");
        txtSucursal.setText("");
        txtdinero.setText("");
    }
    private void txtIdSucuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdSucuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdSucuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text10;
    private javax.swing.JLabel Text11;
    private javax.swing.JLabel Text12;
    private javax.swing.JLabel Text13;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text5;
    private javax.swing.JLabel Text7;
    private javax.swing.JLabel Text9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JButton jbEnviar;
    private com.toedter.calendar.JDateChooser jdFechaSol;
    public javax.swing.JLabel jlNumSoli;
    public javax.swing.JTextField jtNombre;
    public javax.swing.JTextField txtCanSoli;
    public javax.swing.JTextField txtCodProd;
    public javax.swing.JTextField txtIdSucu;
    public javax.swing.JTextField txtPrecio;
    public javax.swing.JTextField txtSucursal;
    public javax.swing.JTextField txtdinero;
    // End of variables declaration//GEN-END:variables
}
