package Visual;

import Clases.Sucursal;
import Clases.SucursalDao;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author david
 */
public class sucursalVisual extends javax.swing.JPanel {
   Sucursal sucu = new Sucursal();
   SucursalDao sucursal = new SucursalDao();
   DefaultTableModel modelo = new DefaultTableModel();
    /**
     * Creates new form sucursalVisual
     */
    public sucursalVisual() {
        initComponents();
        eventoTabla();
        mostrarSucursal();
    }
    
    public void eventoTabla(){
                jtSucursal.addMouseListener(new MouseAdapter()
                {
                 public void mousePressed(MouseEvent Mouse_evt){
                    
                    JTable table = (JTable) Mouse_evt.getSource();
                    Point point = Mouse_evt.getPoint();
                    int row = table.rowAtPoint(point);
                    if (Mouse_evt.getClickCount()==1){
                       jlId.setText(jtSucursal.getValueAt(jtSucursal.getSelectedRow(), 0).toString());
                       txtubicacion.setText(jtSucursal.getValueAt(jtSucursal.getSelectedRow(), 1).toString());
                       txtdireccion.setText(jtSucursal.getValueAt(jtSucursal.getSelectedRow(), 2).toString());
                       txtTelefono.setText(jtSucursal.getValueAt(jtSucursal.getSelectedRow(), 3).toString());
                       txtDescrip.setText(jtSucursal.getValueAt(jtSucursal.getSelectedRow(), 4).toString());
                    }
                }
    });
    }
    
    public void mostrarSucursal(){    
       List<Sucursal> ListarTiendas = sucursal.ListarSucursal();
        modelo = (DefaultTableModel) jtSucursal.getModel();
        Object[] ob = new Object[5];
        for (int i = 0; i < ListarTiendas.size(); i++) {
            ob[0] = ListarTiendas.get(i).getIdSucur();
            ob[1] = ListarTiendas.get(i).getUbicacion();
            ob[2] = ListarTiendas.get(i).getDireccion();
            ob[3] = ListarTiendas.get(i).getTelefono();
            ob[4] = ListarTiendas.get(i).getDescripcion();
            modelo.addRow(ob);
        }
        jtSucursal.setModel(modelo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtSucursal = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        txtubicacion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescrip = new javax.swing.JTextArea();
        txtModificar = new javax.swing.JButton();
        txtAgregar = new javax.swing.JButton();
        txtEliminar = new javax.swing.JButton();
        jlId = new javax.swing.JLabel();
        jbLimpiar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setForeground(new java.awt.Color(102, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtSucursal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Ubicación", "Dirección", "Telefono", "Descripcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtSucursal);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 530, 440));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 550, 460));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 220, 20));

        txtubicacion.setBackground(new java.awt.Color(255, 255, 255));
        txtubicacion.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txtubicacion.setForeground(new java.awt.Color(0, 0, 0));
        txtubicacion.setToolTipText("");
        txtubicacion.setBorder(null);
        add(txtubicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 220, 30));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Ubicación");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("Tiendas");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Direccion");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        txtdireccion.setBackground(new java.awt.Color(255, 255, 255));
        txtdireccion.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txtdireccion.setForeground(new java.awt.Color(0, 0, 0));
        txtdireccion.setToolTipText("");
        txtdireccion.setBorder(null);
        add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 220, 30));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 220, 20));

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Telefono");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        txtTelefono.setBackground(new java.awt.Color(255, 255, 255));
        txtTelefono.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefono.setToolTipText("");
        txtTelefono.setBorder(null);
        add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 230, 30));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 230, 20));

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("Descripción");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        txtDescrip.setBackground(new java.awt.Color(255, 255, 255));
        txtDescrip.setColumns(20);
        txtDescrip.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        txtDescrip.setForeground(new java.awt.Color(0, 0, 0));
        txtDescrip.setLineWrap(true);
        txtDescrip.setRows(5);
        jScrollPane2.setViewportView(txtDescrip);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 230, 90));

        txtModificar.setText("Modificar");
        txtModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModificarActionPerformed(evt);
            }
        });
        add(txtModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, -1));

        txtAgregar.setText("Agregar");
        txtAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgregarActionPerformed(evt);
            }
        });
        add(txtAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        txtEliminar.setText("Eliminar");
        txtEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEliminarActionPerformed(evt);
            }
        });
        add(txtEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, -1, -1));

        jlId.setForeground(new java.awt.Color(255, 255, 255));
        jlId.setText("1");
        add(jlId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 40, -1));

        jbLimpiar.setText("Limpiar");
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });
        add(jbLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 80, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgregarActionPerformed
        // codigo para agregar una nueva sucursal
        if(txtubicacion.getText().equals("") || txtdireccion.getText().equals("") || txtTelefono.getText().equals("") || txtDescrip.getText().equals("") ){
            JOptionPane.showMessageDialog(null, "Todo los campos son requeridos");
            }else{
                    String[] opciones = {"SI","NO"};

                    int n = JOptionPane.showOptionDialog(this,"¿Todo Correcto?","AGREGAR",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,opciones,"");

                    if (n == JOptionPane.YES_OPTION) {
                        //TU CODIGO SI SI
                            String ubi = txtubicacion.getText();
                            String dire = txtdireccion.getText();
                            int tel = Integer.valueOf(txtTelefono.getText());
                            String desc = txtDescrip.getText();
                            
                            sucu.setUbicacion(ubi);
                            sucu.setDireccion(dire);
                            sucu.setTelefono(tel);
                            sucu.setDescripcion(desc);

                           sucursal.insertarSucursal(sucu);
                           JOptionPane.showMessageDialog(null, "Sucursal Registrado");
                           limTable();
                           mostrarSucursal();
                           limTxt();
                            System.out.println("Agregado");
                    }else if (n == JOptionPane.NO_OPTION) {
                        //TU CODIGO SI NO
                          JOptionPane.showMessageDialog(null, "Registrado Cancelado");
                    }
                    
         }
 
    }//GEN-LAST:event_txtAgregarActionPerformed

    private void txtModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModificarActionPerformed
        // Codigo para modificar la sucursal
                              String[] opciones = {"SI","NO"};
      if ("".equals(jlId.getText())) {
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        } else{
            int n = JOptionPane.showOptionDialog(this,"¿Que Desea Hacer?","Modificar",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,opciones,"");

             if (n == JOptionPane.YES_OPTION) {
             if (!"".equals(txtubicacion.getText()) || !"".equals(txtdireccion.getText()) || !"".equals(txtTelefono.getText()) || !"".equals(txtDescrip.getText())) {
                
                sucu.setUbicacion(txtubicacion.getText());
                sucu.setDireccion(txtdireccion.getText());
                sucu.setTelefono(Integer.valueOf(txtTelefono.getText()));
                sucu.setDescripcion(txtDescrip.getText());
                sucu.setIdSucur(Integer.valueOf(jlId.getText()));
                sucursal.modificarSucursal(sucu);
                JOptionPane.showMessageDialog(null, "Sucusal Modificado");
                limTable();
                mostrarSucursal();
                limTxt();

            }
             }else if (n == JOptionPane.NO_OPTION) {
             //TU CODIGO SI NO
             JOptionPane.showMessageDialog(null, "Operacion Cancelada");

        } 
        }
    }//GEN-LAST:event_txtModificarActionPerformed

    private void txtEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEliminarActionPerformed
        // TODO add your handling code here:
                if ("".equals(jlId.getText())) {
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        }else{
          if (!"".equals(jlId.getText())) {
            int pregunta = JOptionPane.showConfirmDialog(null, "Esta seguro de eliminar");
            if (pregunta == 0) {
               int id = Integer.valueOf(jlId.getText());
               sucursal.eliminarSucursal(id);
               limTable();
               mostrarSucursal();
               limTxt();
                }
            }
        }
    }//GEN-LAST:event_txtEliminarActionPerformed

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        // TODO add your handling code here:
        limTxt();
    }//GEN-LAST:event_jbLimpiarActionPerformed
 
    public void limTxt(){
        txtubicacion.setText("");
        txtdireccion.setText("");
        txtTelefono.setText("");
        txtDescrip.setText("");
    }
    public void limTable(){
         DefaultTableModel temp = (DefaultTableModel) jtSucursal.getModel();
    int filas = jtSucursal.getRowCount();

        for (int a = 0; filas > a; a++) {
            temp.removeRow(0);
        }
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JLabel jlId;
    private javax.swing.JTable jtSucursal;
    private javax.swing.JButton txtAgregar;
    private javax.swing.JTextArea txtDescrip;
    private javax.swing.JButton txtEliminar;
    private javax.swing.JButton txtModificar;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtubicacion;
    // End of variables declaration//GEN-END:variables
}
