package Visual;

import Clases.Sucursal;
import Clases.SucursalDao;
import Clases.Usuarios;
import Clases.UsuariosDao;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author david
 */
public class usuariosVisual extends javax.swing.JPanel {
    Usuarios us = new Usuarios();
    Sucursal sucu = new Sucursal();
    SucursalDao sucursal = new SucursalDao();
    
    UsuariosDao usuarios = new UsuariosDao();
    DefaultTableModel modelo = new DefaultTableModel();
    
    /**
     * Creates new form usuariosVisual
     */
    public usuariosVisual() {
        initComponents();
        listarusuarios();
        eventoTable();
        listarSuc();
    }
    
    public void eventoTable(){
                jtUsuarios.addMouseListener(new MouseAdapter()
                {
                 public void mousePressed(MouseEvent Mouse_evt){
                    
                    JTable table = (JTable) Mouse_evt.getSource();
                    Point point = Mouse_evt.getPoint();
                    int row = table.rowAtPoint(point);
                    if (Mouse_evt.getClickCount()==1){
                       txtnombre.setText(jtUsuarios.getValueAt(jtUsuarios.getSelectedRow(), 0).toString());
                       txtApellido.setText(jtUsuarios.getValueAt(jtUsuarios.getSelectedRow(), 1).toString());
                       txtDpi.setText(jtUsuarios.getValueAt(jtUsuarios.getSelectedRow(), 2).toString());
                       txtDireccion.setText(jtUsuarios.getValueAt(jtUsuarios.getSelectedRow(), 3).toString());                     
                       txtTelefono.setText(jtUsuarios.getValueAt(jtUsuarios.getSelectedRow(), 4).toString());
                       txtpass.setText(jtUsuarios.getValueAt(jtUsuarios.getSelectedRow(), 6).toString());
                       jcCargos.setSelectedItem(jtUsuarios.getValueAt(jtUsuarios.getSelectedRow(), 5).toString());
                      jcSucursal.setSelectedItem(jtUsuarios.getValueAt(jtUsuarios.getSelectedRow(), 7).toString());
                    }
                }
    });
    }
    public void listarSuc(){
        jcSucursal.removeAllItems();
        List<Usuarios> listProdu = usuarios.ListarCat();
        
        for (int i = 0; i < listProdu.size(); i++){
            jcSucursal.addItem(String.valueOf(listProdu.get(i).getSucuriduser()));
        }
    }
    
    public void listarusuarios(){
        List<Usuarios> ListarUser = usuarios.ListarUsuarios();
        modelo = (DefaultTableModel) jtUsuarios.getModel();
        Object[] ob = new Object[8];
        for (int i = 0; i < ListarUser.size(); i++) {
            ob[0] = ListarUser.get(i).getNombre();
            ob[1] = ListarUser.get(i).getApellido();
            ob[2] = ListarUser.get(i).getDpiUser();
            ob[3] = ListarUser.get(i).getDireccion();
            ob[4] = ListarUser.get(i).getTelefono();
            ob[5] = ListarUser.get(i).getCargo();
            ob[6] = ListarUser.get(i).getContras();
            ob[7] = ListarUser.get(i).getSucuriduser();
            modelo.addRow(ob);
        }
        jtUsuarios.setModel(modelo);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtUsuarios = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jbLimp = new javax.swing.JButton();
        jbAgregar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbMod = new javax.swing.JButton();
        txtDireccion = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jcCargos = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        txtpass = new javax.swing.JPasswordField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jcSucursal = new javax.swing.JComboBox<>();
        jlSucursal = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtDpi = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Usuarios");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "DPI", "Direccion", "Telefono", "Cargo", "Contraseña", "Sucursal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtUsuarios);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 810, 250));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 830, 290));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Nombre");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Apellido");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("Contraseña");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, 20));

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("Dirección");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setText("Telefono");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 51));
        jLabel8.setText("Sucursal");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, -1, -1));

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 51));
        jLabel9.setText("Cargo");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        jbLimp.setText("Limpiar");
        jbLimp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpActionPerformed(evt);
            }
        });
        add(jbLimp, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });
        add(jbAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });
        add(jbEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        jbMod.setText("Modificar");
        jbMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModActionPerformed(evt);
            }
        });
        add(jbMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        txtDireccion.setBackground(new java.awt.Color(255, 255, 255));
        txtDireccion.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(0, 0, 0));
        txtDireccion.setBorder(null);
        add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 160, 20));

        txtnombre.setBackground(new java.awt.Color(255, 255, 255));
        txtnombre.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        txtnombre.setForeground(new java.awt.Color(0, 0, 0));
        txtnombre.setBorder(null);
        add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 160, 20));

        txtApellido.setBackground(new java.awt.Color(255, 255, 255));
        txtApellido.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(0, 0, 0));
        txtApellido.setBorder(null);
        add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 160, 20));

        txtTelefono.setBackground(new java.awt.Color(255, 255, 255));
        txtTelefono.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefono.setBorder(null);
        add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 160, 20));

        jcCargos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "vendedor", "inventario", "bodega", "administrador" }));
        add(jcCargos, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 160, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 160, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 160, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 160, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 160, 10));

        txtpass.setBackground(new java.awt.Color(255, 255, 255));
        txtpass.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        txtpass.setForeground(new java.awt.Color(0, 0, 0));
        txtpass.setBorder(null);
        add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 160, 20));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 160, 10));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 160, 10));

        jcSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcSucursalActionPerformed(evt);
            }
        });
        add(jcSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, 60, -1));

        jlSucursal.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jlSucursal.setForeground(new java.awt.Color(0, 0, 0));
        add(jlSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 150, 20));

        jLabel10.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 51));
        jLabel10.setText("DPI");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, -1, -1));

        txtDpi.setBackground(new java.awt.Color(255, 255, 255));
        txtDpi.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        txtDpi.setForeground(new java.awt.Color(0, 0, 0));
        txtDpi.setBorder(null);
        add(txtDpi, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 160, 20));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 160, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void jcSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcSucursalActionPerformed
        // TODO add your handling code here:
        int nuevo = Integer.parseInt(String.valueOf(jcSucursal.getSelectedItem()));
        sucu = sucursal.BuscarSucId(nuevo);
        String idT = sucu.getUbicacion();
        jlSucursal.setText(idT);
    }//GEN-LAST:event_jcSucursalActionPerformed

    private void jbModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModActionPerformed
        // TODO add your handling code here:
               String[] opciones = {"SI","NO"};
      if ("".equals(txtDpi.getText())) {
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        } else{
            int n = JOptionPane.showOptionDialog(this,"¿Que Desea Hacer?","Modificar",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,opciones,"");

             if (n == JOptionPane.YES_OPTION) {
             if (!"".equals(txtnombre.getText()) || !"".equals(txtApellido.getText()) || !"".equals(txtTelefono.getText()) || !"".equals(txtpass.getPassword()) || !"".equals(txtDireccion.getText())) {
                
                
                us.setNombre(txtnombre.getText());
                us.setApellido(txtApellido.getText());
                us.setSucuriduser(Integer.valueOf(jcSucursal.getSelectedItem().toString()));
                us.setDireccion(txtDireccion.getText());
                us.setTelefono(Integer.valueOf(txtTelefono.getText()));
                us.setCargo(jcCargos.getSelectedItem().toString());
                us.setContras(String.valueOf(txtpass.getPassword()));
                us.setDpiUser(txtDpi.getText());
                usuarios.ModificarUsuario(us);
                JOptionPane.showMessageDialog(null, "Usuario Modificado");
                limTable();
                listarusuarios();
                limTxt();

            }
             }else if (n == JOptionPane.NO_OPTION) {
             //TU CODIGO SI NO
             JOptionPane.showMessageDialog(null, "Operacion Cancelada");

        } 
        }
    }//GEN-LAST:event_jbModActionPerformed

    private void jbLimpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpActionPerformed
        // TODO add your handling code here:
         limTxt();
    }//GEN-LAST:event_jbLimpActionPerformed

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
        // TODO add your handling code here:
         if(txtnombre.getText().equals("") || txtApellido.getText().equals("") || txtpass.getPassword().equals("") || txtDireccion.getText().equals("") || txtTelefono.getText().equals("") || txtDpi.getText().equals("") ){
            JOptionPane.showMessageDialog(null, "Todo los campos son requeridos");
            }else{
                    String[] opciones = {"SI","NO"};

                    int n = JOptionPane.showOptionDialog(this,"¿Todo Correcto?","AGREGAR",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,opciones,"");

                    if (n == JOptionPane.YES_OPTION) {
                        //TU CODIGO SI SI
                            String nom = txtnombre.getText();
                            String ape = txtApellido.getText();
                            String dpi = txtDpi.getText();
                            Integer sucur = Integer.valueOf(jcSucursal.getSelectedItem().toString());
                            String dire = txtDireccion.getText();
                            int tele = Integer.valueOf(txtTelefono.getText());
                            String cargo = jcCargos.getSelectedItem().toString();
                            String pass = String.valueOf(txtpass.getPassword());

                            
                            us.setNombre(nom);
                            us.setApellido(ape);
                            us.setSucuriduser(sucur);
                            us.setDireccion(dire);
                            us.setTelefono(tele);
                            us.setCargo(cargo);
                            us.setContras(pass);
                            us.setDpiUser(dpi);
                            
                            usuarios.insertarUser(us);
                           JOptionPane.showMessageDialog(null, "Usuario Registrado");
                           limTable();
                           listarusuarios();
                           limTxt();
                            System.out.println("Agregado");
                    }else if (n == JOptionPane.NO_OPTION) {
                        //TU CODIGO SI NO
                          JOptionPane.showMessageDialog(null, "Registrado Cancelado");
                    }
                    
         }
    }//GEN-LAST:event_jbAgregarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // TODO add your handling code here:
        if ("".equals(txtDpi.getText())) {
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        }else{
          if (!"".equals(txtDpi.getText())) {
            int pregunta = JOptionPane.showConfirmDialog(null, "Esta seguro de eliminar");
            if (pregunta == 0) {
                String dpi = txtDpi.getText();
               usuarios.eliminarUsuario(dpi);
               limTable();
               listarusuarios();
               limTxt();
                }
            }
        }
    }//GEN-LAST:event_jbEliminarActionPerformed
   
    public void limTxt(){
        txtnombre.setText("");
        txtApellido.setText("");
        txtpass.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtDpi.setText("");
    }
    
    public void limTable(){
         DefaultTableModel temp = (DefaultTableModel) jtUsuarios.getModel();
    int filas = jtUsuarios.getRowCount();

        for (int a = 0; filas > a; a++) {
            temp.removeRow(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbLimp;
    private javax.swing.JButton jbMod;
    private javax.swing.JComboBox<String> jcCargos;
    private javax.swing.JComboBox<String> jcSucursal;
    private javax.swing.JLabel jlSucursal;
    private javax.swing.JTable jtUsuarios;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDpi;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JPasswordField txtpass;
    // End of variables declaration//GEN-END:variables
}
